vim.keymap.set("n", "<leader>ww", "<Cmd>w<CR>")
vim.keymap.set("n", "<leader>wW", "<Cmd>w!<CR>")
vim.keymap.set("n", "<leader>wq", "<Cmd>wq<CR>")
vim.keymap.set("n", "<leader>wQ", "<Cmd>wq!<CR>")
vim.keymap.set("n", "<leader>q", "<Cmd>q<CR>")
vim.keymap.set("n", "<leader>Q", "<Cmd>q!<CR>")
vim.keymap.set("n", "<leader>E", "<Cmd>Ex<CR>")
vim.keymap.set("n", "<leader>lf", vim.lsp.buf.format)
vim.keymap.set("n", "<leader>ff", "<Cmd>Pick files<CR>")
vim.keymap.set("n", "<leader>h", "<Cmd>Pick help<CR>")
vim.keymap.set("n", "<leader>ts", "<Cmd>set spell!<CR>")
